version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.16-latest
    ports:
      - "9901:9901"
      - "51051:51051"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  opa-envoy:
    image: openpolicyagent/opa:latest-envoy
    ports:
      - "9191:9191"
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"  # default value
      - "--set=decision_logs.console=true"
      - "/policy.rego"
    volumes:
      - ./policy.rego:/policy.rego
      - ./opa.yaml:/opa.yaml
  app:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
